// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDatZeujRrykdrdC6cvohxLgTI8TV41Tyg',
    appId: '1:1036427516914:web:756d2336477d5086b9696b',
    messagingSenderId: '1036427516914',
    projectId: 'matchcraft-matchinggame',
    authDomain: 'matchcraft-matchinggame.firebaseapp.com',
    storageBucket: 'matchcraft-matchinggame.appspot.com',
    measurementId: 'G-9H9T5JC31Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPtChSo1H2NeVJZzXDvq6lAAHPKYTlh_U',
    appId: '1:1036427516914:android:1820c74599368742b9696b',
    messagingSenderId: '1036427516914',
    projectId: 'matchcraft-matchinggame',
    storageBucket: 'matchcraft-matchinggame.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-DCf68_Ti57QIZFCsvLPVTGYrp0oMv1o',
    appId: '1:1036427516914:ios:279bbaa19530acc9b9696b',
    messagingSenderId: '1036427516914',
    projectId: 'matchcraft-matchinggame',
    storageBucket: 'matchcraft-matchinggame.appspot.com',
    iosBundleId: 'com.example.matchCardGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-DCf68_Ti57QIZFCsvLPVTGYrp0oMv1o',
    appId: '1:1036427516914:ios:e25fb91c257fd8c7b9696b',
    messagingSenderId: '1036427516914',
    projectId: 'matchcraft-matchinggame',
    storageBucket: 'matchcraft-matchinggame.appspot.com',
    iosBundleId: 'com.example.matchCardGame.RunnerTests',
  );
}
